### ISSUE TITLE
Rapbian11

### ISSUE THREAD

**Issue by andrerferreira** [Homas/RpiDNS#4]
Hi Homas,

1st time user.

I've just overwritten the variable in ioc2rpz_community_install.sh to allow for Rapbian11 on a Raspberry 4 with a 8GB card.
No issues to report. Rebooting now.

I think the GUI will have some checks against version 10 also, maybe have to try magic there.
Any news regarding supporting it? 

2023-06-27 00:31
#########
RpiDNS was installed
#########

I'll annoyingly update here with blockers and findings

**Comment by andrerferreira** [comment]
aferreira@raspberrypi:~ $ sudo service nginx restart
Failed to restart nginx.service: Unit nginx.service not found.
aferreira@raspberrypi:~ $ sudo service --status-all
 [ - ]  alsa-utils
 [ + ]  avahi-daemon
 [ + ]  bluetooth
 [ - ]  console-setup.sh
 [ + ]  cron
 [ + ]  dbus
 [ + ]  dphys-swapfile
 [ + ]  fake-hwclock
 [ - ]  hwclock.sh
 [ - ]  keyboard-setup.sh
 [ + ]  kmod
 [ + ]  named
 [ + ]  networking
 [ - ]  nfs-common
 [ - ]  paxctld
 [ + ]  php7.4-fpm
 [ + ]  procps
 [ + ]  raspi-config
 [ + ]  rng-tools-debian
 [ - ]  rpcbind
 [ - ]  rsync
 [ + ]  rsyslog
 [ + ]  ssh
 [ - ]  sudo
 [ + ]  triggerhappy
 [ + ]  udev

Curiosity question, why do you need apache2-utils if you use ngix?
in ioc2rpz_community_install.sh 
apt-get  -q -y install php-fpm git openssl sqlite php-sqlite3 apache2-utils

**Comment by andrerferreira** [comment]
dpkg: error processing archive openresty_1.15.8.1-1_arm64.deb (--install):
 package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
 openresty_1.15.8.1-1_arm64.deb
E: Unable to locate package openresty
aferreira@raspberrypi:~ $ apt-cache search openresty
knot-resolver - caching, DNSSEC-validating DNS resolver
lua-nginx-memcached - Pure Lua memcached client driver for the nginx embedded Lua language
lua-nginx-redis - Pure Lua redis client driver for the nginx embedded Lua language
lua-nginx-websocket - Lua websocket client driver for the nginx embedded Lua language

I believe this is the problem... hum

**Comment by andrerferreira** [comment]
Diff issue I just spotted on syslog "lame-servers" (not only fir this sports news website"

Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:67c:1010:35::53#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:690:a00:4001::64#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:660:3005:1::1:2#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2a04:6d80::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:678:20::23#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:500:14:6105:ad::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'record.pt/A/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/A/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/AAAA/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/A/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/A/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/A/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/AAAA/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/AAAA/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/AAAA/IN': 2001:12ff:0:a20::5#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/A/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns4.xl.pt/A/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns4.xl.pt/AAAA/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/A/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/AAAA/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/A/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/AAAA/IN': 2a04:6d82::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns4.xl.pt/A/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/AAAA/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns4.xl.pt/AAAA/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/A/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/A/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.xl.pt/AAAA/IN': 2001:690:a80:4001::100#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/A/IN': 2001:7fd::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.cofina.pt/AAAA/IN': 2001:7fd::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/A/IN': 2001:7fd::1#53
Jun 27 11:09:06 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.cofina.pt/AAAA/IN': 2001:7fd::1#53
Jun 27 11:09:07 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ocsp.godaddy.com/A/IN': 2600:1480:1::40#53
Jun 27 11:09:07 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ocsp.godaddy.com/A/IN': 2603:5:2100::64#53
Jun 27 11:09:07 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ocsp.godaddy.com/A/IN': 2603:5:2200::64#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2001:dcd:2::10#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2001:dcd:1::10#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2610:a1:1074::1:82#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2610:a1:1076::1:82#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2610:a1:1075::1:82#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.weborama.design/A/IN': 2001:dcd:3::10#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2606:4700:50::adf5:3a7e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2606:4700:58::adf5:3b94#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/A/IN': 2606:4700:58::adf5:3b94#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/AAAA/IN': 2606:4700:58::adf5:3b94#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/A/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/A/IN': 2606:4700:58::adf5:3b94#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/AAAA/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/A/IN': 2803:f800:50::6ca2:c194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/AAAA/IN': 2803:f800:50::6ca2:c194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/A/IN': 2a06:98c1:50::ac40:207e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/AAAA/IN': 2a06:98c1:50::ac40:207e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/A/IN': 2a06:98c1:50::ac40:2194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/A/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns3.digitalocean.com/AAAA/IN': 2a06:98c1:50::ac40:2194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2803:f800:50::6ca2:c194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/A/IN': 2803:f800:50::6ca2:c194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2a06:98c1:50::ac40:207e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/A/IN': 2a06:98c1:50::ac40:207e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/AAAA/IN': 2a06:98c1:50::ac40:2194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns1.digitalocean.com/A/IN': 2a06:98c1:50::ac40:2194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.digitalocean.com/AAAA/IN': 2a06:98c1:50::ac40:2194#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.digitalocean.com/AAAA/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns2.digitalocean.com/A/IN': 2803:f800:50::6ca2:c07e#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/A/IN': 2600:9000:5301:4700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/AAAA/IN': 2600:9000:5301:4700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/A/IN': 2600:9000:5303:8700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/AAAA/IN': 2600:9000:5303:8700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/A/IN': 2600:9000:5305:ca00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/AAAA/IN': 2600:9000:5305:ca00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/A/IN': 2600:9000:5307:b00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1593.awsdns-07.co.uk/AAAA/IN': 2600:9000:5307:b00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-504.awsdns-63.com/AAAA/IN': 2600:9000:5302:7f00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-504.awsdns-63.com/AAAA/IN': 2600:9000:5307:c000::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-504.awsdns-63.com/AAAA/IN': 2600:9000:5304:bf00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-504.awsdns-63.com/AAAA/IN': 2600:9000:5301:100::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/AAAA/IN': 2600:9000:5301:e600::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/A/IN': 2600:9000:5306:6700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/AAAA/IN': 2600:9000:5307:a500::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/AAAA/IN': 2600:9000:5303:2700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/A/IN': 2600:9000:5302:e900::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/AAAA/IN': 2600:9000:5305:6500::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/AAAA/IN': 2600:9000:5302:e900::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/A/IN': 2600:9000:5304:2a00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/A/IN': 2600:9000:5305:6500::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/AAAA/IN': 2600:9000:5304:2a00::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-813.awsdns-37.net/A/IN': 2600:9000:5307:a500::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/A/IN': 2600:9000:5300:a700::1#53
Jun 27 11:09:08 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1339.awsdns-39.org/AAAA/IN': 2600:9000:5300:a700::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1877.awsdns-42.co.uk/A/IN': 2600:9000:5303:aa00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1877.awsdns-42.co.uk/A/IN': 2600:9000:5305:ed00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1877.awsdns-42.co.uk/A/IN': 2600:9000:5301:6a00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1877.awsdns-42.co.uk/A/IN': 2600:9000:5307:2e00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-864.awsdns-44.net/A/IN': 2600:9000:5303:2e00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-864.awsdns-44.net/A/IN': 2600:9000:5301:ed00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-864.awsdns-44.net/A/IN': 2600:9000:5305:6c00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-864.awsdns-44.net/A/IN': 2600:9000:5307:ac00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-499.awsdns-62.com/AAAA/IN': 2600:9000:5304:be00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-499.awsdns-62.com/AAAA/IN': 2600:9000:5300:3f00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-864.awsdns-44.net/AAAA/IN': 2600:9000:5303:2e00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-499.awsdns-62.com/AAAA/IN': 2600:9000:5302:7e00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-499.awsdns-62.com/AAAA/IN': 2600:9000:5306:fe00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/A/IN': 2600:9000:5302:cb00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/AAAA/IN': 2600:9000:5302:cb00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/A/IN': 2600:9000:5300:8900::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/AAAA/IN': 2600:9000:5300:8900::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/A/IN': 2600:9000:5304:c00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/AAAA/IN': 2600:9000:5304:c00::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/A/IN': 2600:9000:5306:4900::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving 'ns-1099.awsdns-09.org/AAAA/IN': 2600:9000:5306:4900::1#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.com.edgekey.net/A/IN': 2600:1401:2::42#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.com.edgekey.net/A/IN': 2600:1401:1::41#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.com.edgekey.net/A/IN': 2600:1406:1b::41#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.gigya.com.edgekey.net/A/IN': 2600:1401:2::42#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.gigya.com.edgekey.net/A/IN': 2600:1406:1b::41#53
Jun 27 11:09:09 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.g.akamaiedge.net/A/IN': 2600:1406:32::c2#53
Jun 27 11:09:10 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.eu1.gigya.com/A/IN': 2600:9000:5301:f300::1#53
Jun 27 11:09:10 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.eu1.gigya.com/A/IN': 2600:9000:5307:5500::1#53
Jun 27 11:09:10 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.eu1.gigya.com/A/IN': 2600:9000:5304:4b00::1#53
Jun 27 11:09:10 raspberrypi named[12945]: lame-servers: network unreachable resolving '_.eu1.gigya.com/A/IN': 2600:9000:5303:6000::1#53
Jun 27 11:09:10 raspberrypi named[12945]: lame-servers: network unreachable resolving 'farm5.eu1.gigya.com/A/IN': 2600:9000:5301:f300::1#53

**Comment by andrerferreira** [comment]
"Due to excessively high volume suspicious queries to the IEEE Registration Authority Assignments Downloads server(s), a number of addresses are being blocked. Users are reminded that IEEE RA assignment downloads are limited to one per day. If your access is blocked please contact IEEE Registration Authority ieee-registration-authority@ieee.org to resolve the issue." in anyway related?

**Comment by Homas** [comment]
Many comments/questions :). I'll try to address all of them in a single message.
```
Support 11 and I'll help spread the word. I’ll do a small presentation on it and write an article 4 hackernoon. Then when 12 comes, you look at usage stats and decide if the effort is worth it.
```
Ok. I'll check what I can do.
 
```
Suggestion: Can we have any not resolved/blocked redirected to a website page, rather than a website home page?
```
Yes. In the response-policy settings you can define where to redirect.
In RpiDNS configuration you can also set "Custom Redirect":
<img width="425" alt="image" src="https://github.com/Homas/RpiDNS/assets/13776103/7ac25fb3-5a39-445e-a256-1f22765c9fc9">

```
Offer a default template that states blocked and then let user change it?
This would provide more clarity for the non tech home user IMHO. I can imagine my wife calling me telling me the Internet is broken, me having to investigate and then figuring out it's a blocked resolution.
```
Yes. It is possible not a heavy lift but requires some time to develop :)
```
The challenge, as I understand it, is how to get from a CNAME to do the webpage. Well, can the GUI not handle any requests flagged and display the page? This would remove the configuration step for the domain.
```
You can't get to a specific webpage (it is in the http header) with DNS, but you can redirect to a site which will handle that. E.g. openresty generate a certificate on a fly and can do some other stuff like showing different content based on requested page.

```
As the script is ran as root, it should be fine with the above no? 
```
Yes the script requires root permissions to create folders, change configurations disable/stop services etc.

```
Curiosity question, why do you need apache2-utils if you use nginx?
in ioc2rpz_community_install.sh line 346
apt-get -q -y install php-fpm git openssl sqlite php-sqlite3 apache2-utils
If for compilation only, a clean up step after to remove it?
```
I don't remember why apache2 utils are installed. may be there are some dependencies but of course it can be a mistake. 


```
dpkg: error processing archive openresty_1.15.8.1-1_arm64.deb (--install):
package architecture (arm64) does not match system (armhf)
Errors were encountered while processing:
openresty_1.15.8.1-1_arm64.deb
```
Looks like you installed 32bit version of Raspberry Pi OS and this is the issue.
Because you got Raspberry 4/8Gb (I assume in your first message it was RAM) I highly recommend to install 64-bit version due to better performance and full RAM access (32 bit version can access only 4Gb RAM).

```
I believe this is the problem... hum... there's a 1.21.4.2 RC1 out
```
Yes. It is a bit outdated but there was an extra patch i had to apply just for that version. I'm not sure if it is still needed - have to check.

```
Jun 27 11:21:15 raspberrypi named[12945]: lame-servers: network unreachable resolving 'cash.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:7e2#53
Jun 27 11:21:15 raspberrypi named[12945]: lame-servers: network unreachable resolving 'wanda.ns.cloudflare.com/A/IN': 2400:cb00:2049:1::a29f:7e2#53
Jun 27 11:21:15 raspberrypi named[12945]: lame-servers: network unreachable resolving 'cash.ns.cloudflare.com/AAAA/IN': 2400:cb00:2049:1::a29f:7e2#53
Jun 27 11:21:15 raspberrypi named[12945]: lame-servers: network unreachable resolving 'wanda.ns.cloudflare.com/AAAA/IN': 2400:cb00:2049:1::a29f:7e2#53
```
Looks like you don't have IPv6 but bind tries to resolve some queries via IPv6.

**Comment by Homas** [comment]
@andrerferreira just released RpiDNS for Rapbian11 32-bits (Raspberry OS 11). It may work on 32-bits 64-bits but I didn't test it yet.

**Comment by Homas** [comment]
RpiDNS is supported on Rapbian11 64-bits (Raspberry OS 11)
