### ISSUE TITLE
From LOG2RAM to externad HD

### ISSUE THREAD

**Issue by andrerferreira** [Homas/RpiDNS#5]
I've noticed a check on the installation script for log2ram, but it assumes, if I understand it correctly, that it has to already be installed... well it didn't and I've not seen instructions for it, nonetheless my query/feature request would be to have all logs configured so they are moved to a mount external HD as to save the life of the poor raspberry card.
Will it be very hard to achieve perhaps via configuration script flag/command line parameter?

Cheers!

**Comment by Homas** [comment]
1. log2ram is installed by the script. There is a dependency on dist version 
2. You can mount the following directories to your HDD
```
/var/log
/var/cache/bind
/opt/rpidns/logs
/opt/rpidns/conf/ssl_cache
/opt/rpidns/www/db
```
3. Actually if you buy a good sd-card it should work for many years. It is based on my experience running RpiDNS and OpenWRT on 2 Raspberry Pi 4.
